### ISSUE TITLE
Expand lintr description

### ISSUE THREAD

**Issue by CaitlinA** [Burke-Lauenroth-Lab/workflow_guidelines#2]
In the R Style Guide section could expand on what exactly lintr is currently checking for? Or anything else you think is necessary here.

**Comment by dschlaep** [comment]
I would refer to
- https://github.com/jimhester/lintr
- ?lint documentation
- our tests in `test_rSFSW2_StyleSpelllingPractices.R` and mention that they are skipped on cran, , on appveyor, and if the the `lintr` package version is less than `1.0.2.9000`
- the file exclusions mentioned in that test file
- the settings in `.lintr`
