### ISSUE TITLE
Code Development

### ISSUE THREAD

**Issue by CaitlinA** [Burke-Lauenroth-Lab/workflow_guidelines#4]
I could use some help with my code development guidelines/tips. Can you check out what I wrote in the __R__ section? I am trying to keep it broad, but it still seems to mostly pertain to rSFSW2. Anything you could add?

I have yet to write anything for C. Do you have any good recommendations?

**Comment by dschlaep** [comment]
I'm not sure what you intend to add here: much of the recommendations in the R section seem also ti apply to writing c code and anything specific is in the READMEs of each project, e.g., for `SOILWAT2` and `rSOILWAT2`
